pipeline {
    agent any

    stages {
        stage('Clonar o repositorio') {
            steps {
                git branch: 'main', url: 'https://github.com/FelipeRBDantas/TCC-EBAC.git'
            }
        }
        stage('Instalar dependencias') {
            steps {
                bat 'cd /teste-api && npm install'
            }
        }
        stage('Executar testes') {
            steps {
                bat 'npm run cy:run'
            }
        }
    }
}
